### ISSUE TITLE
设置窗口日期问题

### ISSUE THREAD

**Issue by yanquanyu** [zx1984/calendar-price-jquery#1]
当插件设置比如endDate时间为2017-08-01日，在设置窗口显示的日期内输入2018-08-01，那么最后获取到的数组一直包含到2018-08-01的记录。

**Comment by capricorncd** [comment]
做了一些修改，不知道是不是你要的需求，麻烦更新到最新版本测试一下。
或者你再截图阐述一下你的问题，对你想要表达的意思不是很理解 ...

**Comment by yanquanyu** [comment]
才看到，我的意思就是配置参数中endDate设置为2017-08-01，但是在设置按钮弹出来的窗口中的时间范围的日期中输入2018-08-01，也就是超过了endDate设置的日期，最后获取到的json数组中，包含了一直到2018-08-01的数据，我感觉这块是不是应该只能获取到endDate设置的最大时间

另外是否还可以增加一个配置或者函数，自定义一个时间范围内的颜色，比如自定义前20天的背景色为绿色这样的
