### ISSUE TITLE
不能多次异步绑定日历数据

### ISSUE THREAD

**Issue by ian-gge** [zx1984/calendar-price-jquery#2]
因为一次性返回的数据太多了，所以想做成每点击下一个月next-month或者上一月的时候，就异步请求后台接口，但是请求回来后，数据不能绑定到日历当中。

本人jq比较差，想请教一下楼主

**Comment by capricorncd** [comment]
新增参数monthChage: function(){}，返回切换前月份数据；
新增方法:
  update(newData)更新日历数据, 
  getMonthData()获取当月数据。
// ===========
详见demo，或文档。

**Comment by ian-gge** [comment]
谢谢大神
