### ISSUE TITLE
您好，想请问一下插件一些问题

### ISSUE THREAD

**Issue by MIMSC** [zx1984/calendar-price-jquery#6]
您好，插件可否设置某个参数只在日历上显示，但是不可以进行编辑。例如酒店系统，我想在日历上显示价格和剩余房间数。编辑的时候就只显示出价格可以编辑，剩余房间数不显示。 目前是在 config 里不写剩余房间数的配置的话，在设置完成后 日历上的剩余房间数 就会变成 {key} 这种样式了

**Comment by capricorncd** [comment]
你在插件实例化后，或者编辑窗口显示前，用$('input[name="xxxxKey"]').hide()使其输入框不显示？

**Comment by MIMSC** [comment]
是的呢，我目前就是使用了隐藏方法 把不要编辑的内容隐藏了起来




------------------ 原始邮件 ------------------
发件人: "Capricorncd"<notifications@github.com>;
发送时间: 2018年12月2日(星期天) 凌晨0:15
收件人: "capricorncd/calendar-price-jquery"<calendar-price-jquery@noreply.github.com>;
抄送: "空城、旧梦﹌"<1293719114@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [capricorncd/calendar-price-jquery] 您好，想请问一下插件一些问题 (#6)




你在插件实例化后，或者编辑窗口显示前，用$('input[name="xxxxKey"]').hide()使其输入框不显示？

**Comment by capricorncd** [comment]
* config: `Array` (必须)，与data中的数据参数(属性)对应，该配置里的配置项，即可设置的参数字段，`key` 为需要设置的字段，`name`为输入框前面显示的名称。

|元素字段|类型|必须|说明|
|:--|:--|:--|:--|
|disabled|boolean|否|是否禁用input输入，默认为`false`|
|editable|boolean|否|是否显示该项input，默认为`true`|

**Comment by MIMSC** [comment]
您好，我今天才看到邮件，我看到后去试了一下，发现对于我提出的那类需求，好像还是无法实现，两个参数我都有试着使用， 禁用input框输入，对单个编辑的时候没问题，但是如果进行批量编辑的话，就会出现我后面的日期的剩余房数，都会变成我当前点击的那个日期的剩余房间数，但这个剩余房间数 我其实是不能进行一个编辑改动的。editable 这个参数的话，我隐藏起来了剩余房间数的编辑框，但是在我点击确定后，日历上的剩余房间数还是会变成{key}这种形式。能不能就是在config的参数里面我写了那个key，那个key的值才会被编辑改动，其它的值保持原样，或者是在我给某个key加上一个参数，在编辑的时候既不出现编辑框，在点击确定的时候也不会修改这个key的值







------------------ 原始邮件 ------------------
发件人: "Capricorncd"<notifications@github.com>;
发送时间: 2018年12月7日(星期五) 晚上9:31
收件人: "capricorncd/calendar-price-jquery"<calendar-price-jquery@noreply.github.com>;
抄送: "空城、旧梦﹌"<1293719114@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [capricorncd/calendar-price-jquery] 您好，想请问一下插件一些问题 (#6)



 
config: Array (必须)，与data中的数据参数(属性)对应，该配置里的配置项，即可设置的参数字段，key 为需要设置的字段，name为输入框前面显示的名称。
     元素字段 类型 必须 说明 
    disabled boolean 否 是否禁用input输入，默认为false 
  editable boolean 否 是否显示该项input，默认为true

**Comment by MIMSC** [comment]
您好，我今天才看到邮件，我看到后去试了一下，发现对于我提出的那类需求，好像还是无法实现，两个参数我都有试着使用， 禁用input框输入，对单个编辑的时候没问题，但是如果进行批量编辑的话，就会出现我后面的日期的剩余房数，都会变成我当前点击的那个日期的剩余房间数，但这个剩余房间数 我其实是不能进行一个编辑改动的。editable 这个参数的话，我隐藏起来了剩余房间数的编辑框，但是在我点击确定后，日历上的剩余房间数还是会变成{key}这种形式。能不能就是在config的参数里面我写了那个key，那个key的值才会被编辑改动，其它的值保持原样，或者是在我给某个key加上一个参数，在编辑的时候既不出现编辑框，在点击确定的时候也不会修改这个key的值
